### ISSUE TITLE
Issue installing on unix (wrong path)

### ISSUE THREAD

**Issue by kpoman** [elisemercury/AutoClean#7] opened 2022-07-15 13:05 UTC
Hello,
I had some issues installing on linux via pip. See below:

> (data-analyst) kpoman@kpoman-ThinkPad-P50:~$ pip install py-AutoClean
> Collecting py-AutoClean
>   Using cached py-AutoClean-1.1.0.tar.gz (10 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-ab6r4pni/py-autoclean_df4e3dbbe1f74f57812c1e51def669aa/setup.py", line 9, in <module>
>           exec(open('autoclean/version.py').read())
>       FileNotFoundError: [Errno 2] No such file or directory: 'autoclean/version.py'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> (data-analyst) kpoman@kpoman-ThinkPad-P50:~$

I had to manually download the tarball, uncompress, create a symlink from AutoClean to autoclean (notice different case), and then it built and installed without problem.

**Comment by elisemercury** [comment] 2022-07-20 14:23
Hi @kpoman,
Thanks a lot for your feedback and for opening the issue! I will have a look at it and do some testing to fix the issue. Happy you managed to fix it meanwhile yourself. I'll let you know when it's fixed with the next release!
Again thanks and all the best,
Elise

**Comment by bruckwubete** [comment] 2022-07-28 03:30
@elisemercury created PR here to fix this 'case' issue: https://github.com/elisemercury/AutoClean/pull/8

**Comment by elisemercury** [comment] 2022-07-29 14:01
Hi @kpoman,
The issue had now been resolved with version v1.1.2 and the installation on UNIX should work without issues. In case you should still face some issue, please feel free to let me know again so I can have a look at it!
All the best,
Elise

**Closed as completed by elisemercury** 2022-07-29 14:01 UTC
Labels: bug

**Comment by rroline** [comment] 2022-08-17 19:39
@kpoman  - Would you be so kind as to share an example of your solution? I am attempting to install this package in a docker container and it seems like the pathing is causing issues. Wondering if setting up a symbolic link will fix it. Any help would be greatly appreciated. Thanks!

**Comment by kpoman** [comment] 2022-08-17 22:27
@rroline you should pip download Py-AutoClean ... you'll obtain a tarball that you will uncompress, then python setup.py build, then simlink then install. But anyway, as stated by @elisemercury it does work out of the box now for v1.1.2 !!!!

**Comment by rroline** [comment] 2022-08-17 22:34
@kpoman - thank you for the quick reply! I was unable to install it via pip on Ubuntu 20.04 nor was I able to add the package to requirements.txt and build it into the docker image. 

The issue is that the setup.py file has static paths to the locations of files within the package. In both cases, it did not dynamically pickup the first part of the path and failed. I was able to build it manually into my project from scratch - and appreciate the help. This package is great work - @elisemercury thanks for creating something so awesome and useful! :)
